/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as NossaHistoriaRouteImport } from './routes/nossa-historia'
import { Route as MarcasRouteImport } from './routes/marcas'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AreaDeAtuacaoRouteImport } from './routes/area-de-atuacao'
import { Route as IndexRouteImport } from './routes/index'

const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const NossaHistoriaRoute = NossaHistoriaRouteImport.update({
  id: '/nossa-historia',
  path: '/nossa-historia',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasRoute = MarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaDeAtuacaoRoute = AreaDeAtuacaoRouteImport.update({
  id: '/area-de-atuacao',
  path: '/area-de-atuacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/area-de-atuacao': typeof AreaDeAtuacaoRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/marcas': typeof MarcasRoute
  '/nossa-historia': typeof NossaHistoriaRoute
  '/produtos': typeof ProdutosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/area-de-atuacao': typeof AreaDeAtuacaoRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/marcas': typeof MarcasRoute
  '/nossa-historia': typeof NossaHistoriaRoute
  '/produtos': typeof ProdutosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/area-de-atuacao': typeof AreaDeAtuacaoRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/marcas': typeof MarcasRoute
  '/nossa-historia': typeof NossaHistoriaRoute
  '/produtos': typeof ProdutosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/area-de-atuacao'
    | '/contato'
    | '/empresa'
    | '/marcas'
    | '/nossa-historia'
    | '/produtos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/area-de-atuacao'
    | '/contato'
    | '/empresa'
    | '/marcas'
    | '/nossa-historia'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/area-de-atuacao'
    | '/contato'
    | '/empresa'
    | '/marcas'
    | '/nossa-historia'
    | '/produtos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreaDeAtuacaoRoute: typeof AreaDeAtuacaoRoute
  ContatoRoute: typeof ContatoRoute
  EmpresaRoute: typeof EmpresaRoute
  MarcasRoute: typeof MarcasRoute
  NossaHistoriaRoute: typeof NossaHistoriaRoute
  ProdutosRoute: typeof ProdutosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nossa-historia': {
      id: '/nossa-historia'
      path: '/nossa-historia'
      fullPath: '/nossa-historia'
      preLoaderRoute: typeof NossaHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas': {
      id: '/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof MarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-de-atuacao': {
      id: '/area-de-atuacao'
      path: '/area-de-atuacao'
      fullPath: '/area-de-atuacao'
      preLoaderRoute: typeof AreaDeAtuacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreaDeAtuacaoRoute: AreaDeAtuacaoRoute,
  ContatoRoute: ContatoRoute,
  EmpresaRoute: EmpresaRoute,
  MarcasRoute: MarcasRoute,
  NossaHistoriaRoute: NossaHistoriaRoute,
  ProdutosRoute: ProdutosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
